version: '3'

services:
  frontend:
    build: ./frontend
    networks:
      - ctf-network
    # Expose the frontend to the host
    ports:
      - "80:80"

  backend:
    build: ./backend
    networks:
      - ctf-network
    # Remove port exposure - backend should only be accessible through frontend

networks:
  ctf-network:
    driver: bridge 